name: 'swin_v2'
model_args:
    img_size: 256
    patch_size: 4
    in_chans: 3
    num_classes: 2
    embed_dim: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 8
    mlp_ratio: 4.
    qkv_bias: True
    drop_rate: 0.
    attn_drop_rate: 0.
    drop_path_rate: 0.1
    ape: False
    patch_norm: True
ckpt_path: null
    
    

