# default config
defaults:
    - dataset: baseline
    - training: baseline
    - _self_

model:
    model_name: 'swin_v2_t'
    model_args:
        num_classes: 2
        weights: 'DEFAULT'

# additional config
run_name: 'cluster_dev_run'
lightning_log_dir: '../lightning-logs/rare25/baseline'
random_seed: 666

# override config
dataset:
    batch_size: 16
    num_workers: 8

training:
    accelerator: 'gpu'
    devices: 1
    fast_dev_run: True