# default config
defaults:
    - dataset: baseline
    - model: baseline_swinv2
    - training: baseline
    - _self_

# additional config
run_name: 'baseline_swinv2'
lightning_log_dir: '../lightning-logs/rare25/baseline'
random_seed: 666

# override config
dataset:
    batch_size: 32
    num_workers: 8

training:
    accelerator: 'gpu'
    devices: 1
    fast_dev_run: True