# default config
defaults:
    - dataset: baseline
    - training: baseline
    - _self_

model:
    model_name: 'convnext_small'
    model_args:
        num_classes: 2
        weights: 'IMAGENET1K_V1'
    loss_name: 'cross_entropy'
    loss_args: {}
    use_lora: false
    lora:
        r: 16
        alpha: 32
        dropout: 0.1
        
# additional config
run_name: 'convnext_small'
lightning_log_dir: './lightning-logs/rare25/baseline'
random_seed: 666

# override config
dataset:
    batch_size: 32
    num_workers: 8
    preprocessing:
        resize:
            size: 
                - 224
                - 224

training:
    accelerator: 'gpu'
    devices: 1
    fast_dev_run: False
    max_epochs: 300
