# default config
defaults:
    - dataset: baseline
    - training: baseline
    - _self_

model:
    model_name: 'swin_v2_t'
    model_args:
        num_classes: 2
        weights: 'DEFAULT'
    loss_name: 'focal_loss'
    loss_args: {}
        

# additional config
run_name: 'mps_dev_run'
lightning_log_dir: './lightning-logs/rare25/baseline'
random_seed: 666

# override config
dataset:
    batch_size: 4
    num_workers: 4

training:
    accelerator: 'mps'
    devices: 1
    fast_dev_run: True