# default config
defaults:
    - dataset: baseline
    - training: baseline
    - _self_

model:
    model_name: 'swin_v2_b'
    model_args:
        num_classes: 2
        weights: 'IMAGENET1K_V1'
    loss_name: 'contropy_loss'
    loss_args: {alpha: 0.01}
    use_lora: true
    lora:
        r: 16
        alpha: 32
        dropout: 0.1

# additional config
run_name: 'swin_big_lora'
lightning_log_dir: './lightning-logs/rare25/LoRA'
random_seed: 666

# override config
dataset:
    batch_size: 32
    num_workers: 8
    preprocessing:
        resize:
            size: 
                - 224
                - 224

training:
    accelerator: 'gpu'
    devices: 1
    fast_dev_run: False
    max_epochs: 300