# default config
defaults:
    - dataset: baseline
    - training: baseline
    - _self_

model:
    model_name: 'swin_v2_t'
    model_args:
        num_classes: 2
        weights: 'IMAGENET1K_V1'
    loss_name: 'cross_entropy'
    loss_args: {}

# additional config
run_name: 'swin_v2'
lightning_log_dir: '../lightning-logs/rare25/baseline'
random_seed: 666

# override config
dataset:
    batch_size: 32
    num_workers: 8
    preprocessing:
        resize:
            size: 
                - 256
                - 256

training:
    accelerator: 'gpu'
    devices: 1
    fast_dev_run: False
    max_epochs: 300
    optimizer:
        lr: 0.00002